### ISSUE TITLE
Class as type and typeof remains problematic

### ISSUE THREAD

**Issue by alloy** [alloy/flow2dts#24]
With our current `$TypeOf` helper we can successfully convert `typeof SomeClass` back to a constructor function, but we cannot use it to annotate a variable to contain an _instance_ of `SomeClass`.

See [this playground](https://www.typescriptlang.org/play?#code/PQKhCgAIUgzAbA9gdwEwBMAuBnSBXTAS3kMwE9JyAHAUyhGHHGpsgBIAVM2geVgB4OAPkgBeSB0g0AHphoA7dLgDekeTWSQAFADo9AQwBOAc2wAuSPvlkAlBasUAvpAD8kAJLzsmKwGMaXLSCIgBkEpAWHEygENCQAMKI8gBuNIZy6JCGNPq+mAC08vpEqZTchPKm9Izg6DS+8EasDfrYuADKiAC2NPGNbZDKUJAj3sWEvpDY3TTtPkS+ALI0mAAWiOhadpDJiITow6MznmPy-strG1sWu-vgjtFg9JAASjT5MlSI6drZuQVFEo0YAVOrSHToHQ4GzVJh1FrZSC+JLeSCdHp9VrYN6fb4ZCycbg0Pj8FiIWBomaYtpCR6xGAAVWw+mMdGgNXRvX62JouPSNEh0x6c3GSxW602MPUmk51J5fIyWx0QpoJx8ZxoFwlW3AwGAElWhFwsH0xGw4GRXkwkGkBMCxIEZIpsu5OOkX356BE4mllIxrt57rxAq2QA)

I'm afraid I see no other solution than actually scan the entire code base and record all exported classes and then convert Flow code to _not_ use `typeof` on classes. Which also means we can remove the `$TypeOf` type altogether.

**Comment by alloy** [comment]
Actually I did find a way to recombine the types into a usable class, which is to extend the created type into a class. See [this playground](https://www.typescriptlang.org/play?#code/PQKhCgAIUgzAbA9gdwEwBMAuBnSBXTAS3kMwE9JyAHAUyhGHHGpsgBIAVM2geVgB4OAPkgBeSB0g0AHphoA7dLgDekeTWSQAFADo9AQwBOAc2wAuSPvlkAlBasUAvpAD8kAJLzsmKwGMaXLSCIgBkEpAWHEygENCQAMKI8gBuNIZy6JCGNPq+mAC08vpEqZTchPKm9Izg6DS+8EasDfrYuADKiAC2NPGNbZDKUJAj3sWEvpDY3TTtPkS+ALI0mAAWiOhadpDJiITow6MznmPy-strG1sWu-vgjtFg9JAASjT5MlSI6drZuQVFEo0YAVOrSHToHQ4GzVJh1FrZSC+JLeSCdHp9VrYN6fb4ZCycbg0Pj8FiIWBomaYtpCR6xGAAVWw+mMdGgNXRvX62JouPSNEh0x6c3GSxW602MPUmk51J5fIyWx0QpoJx8ZxoFwlW3AwGAElWhFwsH0xGw4GRXkwkGkBMCxIEZIpsu5OOkX356BE4mllIxrt57rxAp1cPqjURLQGAA0pLIFEo-VysW6PRlBg94RHmtzINHUHG5IoOlSAwqBRmmNHlTMRQstVcpRo80qVWq-JrxY2LSjrdJbXmCz7m9Gdf2az12xqG5KgA). Alas I don’t see a way to do this statically.

**Comment by ZihanChen-MSFT** [comment]
```typescript
declare class X extends SomeClassReexported {}
```

X does not exist in Javascript we want to annotate so this eventually will fail, so it is not a valid idea.

**Comment by ZihanChen-MSFT** [comment]
Actually the real issue we are facing to is that, assume we have a class:
```typescript
class A{}
```

And we want to create a TypeScript semantic object `B`, so that all following code works:
```typescript
var o1 : A = new A();
var o2 : A = new B();
var o3 : B = new A();
var o4 : B = new B();
```

Actually this is impossible. So I think maybe we just cannot use the form of `$TypeOf<typeof T>` from the beginning. Since we cannot copy a class (not meaning copy a class instance), so `the code of variable type` and `the code of constructor` must be different code. We tried to use the same code `$TypeOf<typeof T>` to be both a type and a constructor, this is not going to work.

**Comment by ZihanChen-MSFT** [comment]
My conclusion for now is that, when we see a Flow declaration:
```typescript
declare const Aliased: typeof Something
```
It could be a variable, or a type.

Assume we change `$TypeOf<T>` to `T extends {new(...args:infer U)} ? U : T`, which returns the type not the type constructor.

- When `Aliased` is a variable, we generate `$TypeOf<typeof Something>`
- When `Aliased` is an internal-used type alias, since there is not `new T` in declaration file, we replace all `Aliased` to `$TypeOf<typeof Something>`
- When `Aliased` is an exported type alias
  - When `Something` is a type, we generate `export {Something as Aliased}`
  - When `Something` is a variable, we cannot translate this code, because the real class type of `Something` must be exportable, and it is not easy even with TypeScript Compiler API to generate a correct import clause from who knows where the file is. So generate `export type Aliased = $TypeOf<typeof Something>` and hope people don't want `new Aliased()`

The point is that, we cannot copy a class in TypeScript, so when Facebook uses `declare const Aliased: typeof Something` to import-rename-export, the only choice for us is to do the same renaming in `export` statement, and skip all intermediate steps of renaming, just like what we are doing now.

But when it is only used to do import-rename, then this `$TypeOf` version is efficient, we don't need to care about what `Something` is.

**Comment by alloy** [comment]
> Actually this is impossible. So I think maybe we just cannot use the form of `$TypeOf<typeof T>` from the beginning. Since we cannot copy a class (not meaning copy a class instance), so the code of variable type and the code of constructor must be different code. We tried to use the same code `$TypeOf<typeof T>` to be both a type and a constructor, this is not going to work.

Correct, this is the issue. In TS a class symbol can refer to both a type and a value and there is no way for us to recombine them into that once it has been used with `typeof`.

**Comment by alloy** [comment]
Running this question by some other TS people before we go and change the architecture to find and track all classes across module boundaries.

**Comment by alloy** [comment]
> Running this question by some other TS people before we go and change the architecture to find and track all classes across module boundaries.

Alternatively we can ask `flow` for the definition of a reference and lazily parse the definition, which might be a simpler workaround as we don't need to manually resolve all intermediate imports-exports.

For example, the following command that asks for the definition of [the reference here](https://github.com/alloy/flow2dts/blob/45d167efca721dbb0298806b0ae91c94fc033413/workbench/react-native/v0.63.3/inputs/index.js.flow#L50) points to [this definition](https://github.com/alloy/flow2dts/blob/45d167efca721dbb0298806b0ae91c94fc033413/workbench/react-native/v0.63.3/inputs/Libraries/Utilities/Dimensions.js.flow#L2)

```
~/C/R/f/w/r/v0.63.3 [main] » flow get-def inputs/index.js.flow 50 15
/Users/eloy/Code/ReactNative/flow2dts/workbench/react-native/v0.63.3/inputs/Libraries/Utilities/Dimensions.js.flow:2:15,2:24
```

**Comment by ZihanChen-MSFT** [comment]
`flow get-def` seems great. I think we could do this in several pass, acceptable if they must be done in multiple commands:

- Run babel and enumerate all identifiers and all declarations, print to a file
- Following the file and run `flow get-def` to get all results, print to another file
- Merge these two file into a hint file
- Run our transpiler with this hint file. Now whenever we see an identifier, we know what it is (e.g. is that a class?), and where it comes from (could used to generate import decalarations)

**Comment by alloy** [comment]
Come to think of it, that sounds pretty much like what the LSP would offer. Seeing as Flow needs to do a full check to make `get-def` to work, we might as well just let it do all that other work too?

**Comment by ZihanChen-MSFT** [comment]
Just checked our workbench, no variable is exported as a type alias, which is a good news.

I think this new technology could help us remove all `declare var` in our output. The point is that, it is not enough just to know which identifier refer to which class, because that class may be exported multiple times and eventually be imported to the current file.

We can still keep our current implementation of resolving an identifier all the way to an import statement. But we use the hint so that we don't need to write `$TypeOf<typeof Something>` when we know it is a type. And when it is not a type, we just write `typeof Something`.

So for the hint file, I suggest we just record "if this identifier is a type". And we need to take care of entity names like "A.B.C", we need to resolve every level of it.
