### ISSUE TITLE
$ObjMap with complex function types cannot be converted

### ISSUE THREAD

**Issue by alloy** [alloy/flow2dts#9]
Our conversion will only support cases where the function doesn't actually consider the input type, which luckily are the only cases that RN uses at this time.

https://github.com/alloy/flow2dts/blob/d6f3400be79b5d5ffe40fd9f93d59300eb889aac/packages/flow2dts/src/transform/rewriteTypeVisitors/typeReferenceVisitor.ts#L68-L93

So this works:

```ts
type MappedTyped = $ObjMap<T, () => boolean>
```

See https://github.com/piotrwitek/utility-types/issues/18

**Comment by alloy** [comment]
I’m starting to wonder if it would make more sense to use overrides for these few cases instead of partially supporting the feature 🤔

@ZihanChen-MSFT What do you think?

**Comment by ZihanChen-MSFT** [comment]
Just checked all the input we have, it is just 4 `$ObjMap` and `$ObjMapi` cases and the return type of the second argument is static. I think it should be fine.

I think we are choosing between:
- Only handling these simple cases, reporting errors when it is too complex
- Totally not handling it and use override

I actually prefer the first one, but we need to twist it so that there are still chances to use override for complex cases. Reporting error will ruin the output file.

**Comment by alloy** [comment]
> I actually prefer the first one, but we need to twist it so that there are still chances to use override for complex cases. 

Good call. Seeing as Flow does not have any other form of mapping types, I think it's indeed fair to assume that often the mapper function type will actually be static, in which case we can indeed just use the `ReturnType`.

**Comment by alloy** [comment]
Done in https://github.com/alloy/flow2dts/commit/f54aee94bcab89d3b313a33ec9bf42a72a8a9835
